name: Link Checker 

on:
  workflow_dispatch: 
    inputs:
      deployment:
        description: 'ballerina.io deployment environment'
        required: true
        default: 'live'
        type: choice
        options:
        - ballerina.io (live)
        - ballerina.io (preprod)
        - lib.ballerina.io (live)
        - lib.ballerina.io (staging)
        - lib.ballerina.io (dev)

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v3
    - name: Run link checker
      env:
        DEPLOYMENT: ${{ inputs.deployment }}
      run: |
        npm install --global @deptagency/octopus
        
        URL=https://ballerina.io/ 

        if [ "$DEPLOYMENT" == "ballerina.io (preprod)" ]; then
          URL=https://pre-prod.ballerina.io/
        fi

        if [ "$DEPLOYMENT" == "lib.ballerina.io (live)" ]; then
          URL=https://lib.ballerina.io/
        fi

        if [ "$DEPLOYMENT" == "lib.ballerina.io (staging)" ]; then
          URL=https://staging-lib.ballerina.io/
        fi

        if [ "$DEPLOYMENT" == "lib.ballerina.io (dev)" ]; then
          URL=https://dev-lib.ballerina.io/
        fi

        octopus $URL
