name: Spell Check

on:
  # Run on-demand using workflow_dispatch
  workflow_dispatch:
  # Schedule to run once a week
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC

jobs:
  spelling:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3 # Using a specific version of checkout

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install spell checker
        run: |
          pip install check-spelling==0.0.20 # Use a specific version of the spell checker

      - name: Run spell checker
        uses: check-spelling/check-spelling@0.0.19 # Pin the check-spelling action to a specific version
        with:
          paths: |
            _data/**
          exclude: |
            *.lock
            *.json
            *.yaml
            *.yml
            *.png
            *.jpg
            *.svg
          extra_dictionaries: .spelling

      - name: Create spell check report
        id: spellcheck_report
        run: |
          echo "### Spell Check Report" > report.md
          echo "Found spelling issues in the following files:" >> report.md
          cat .github/actions/spellcheck_output.txt >> report.md

      - name: Archive the spell check report
        uses: actions/upload-artifact@v3 # Pin the upload-artifact action to a specific version
        with:
          name: spell-check-report
          path: report.md
