name: Create PR for new Swan Lake BBEs pages on distribution repo changes

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
        run: node --version
