name: Test run for github actions workflow

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install dependencies
        run: npm i

      - name: Clone distribution repository
        run: git clone https://$GITHUB_TOKEN@github.com/Ballerina-By-Examples/ballerina-dev-website.git

      - name: Copy examples to dev website repo
        run: cp -r /ballerina-distribution/examples .

      - name: Run markdown to HTML generation script
        run: node /js/markdownConverter.js /examples /learn/by-example
