name: Test run for github actions workflow

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Install dependencies
        run: npm i

      - name: Clone distribution repository
        run: git clone https://$GITHUB_TOKEN@github.com/Ballerina-By-Examples/ballerina-distribution.git

      - name: Copy examples to dev website repo
        run: cp -r ./ballerina-distribution/examples .

      - name: Run markdown to HTML generation script
        run: node ./js/markdownConverter.js ./examples ./learn/by-example

      - name: Push changes to the pr-branch
        run: |
          git checkout -b pr-branch || git checkout pr-branch
          git pull --ff-only
          git checkout master
          git merge -s ours pr-branch
          git checkout pr-branch
          git merge master

          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}

          git push -u origin pr-branch

      - name: Create pull request for new BBEs
        shell: bash
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          bin/hub pull-request -b master -m '[Automated] Update Ballerina By Example(BBEs) pages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
